const playlist = [
  { singer: "Maluma", song: "Despacito" },
  { singer: "Lynyrd Skynyrd", song: "Free bird" },
  { singer: "Noa Kirel", song: "Diamonds" },
  { singer: "ACDC", song: "Thunderstruck" },
  { singer: "metallice", song: "One" },
  { singer: "metallice", song: "Master of Puppets" },
  { singer: "metallice", song: "nothing else matters" },
  { singer: "metallice", song: "Fade to black" },
  { singer: "billy eylish", song: "the bad guy" },
  { singer: "dream theater", song: "octavarium" },
  { singer: "dream theater", song: "as I am" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
  { singer: "metallice", song: "The masses" },
];
